baseURL = 'https://awesome-video-prompts.pages.dev/'
relativeURLs = true
canonifyURLs = false
title = 'Awesome Video Prompts'
theme = 'ananke'

enableRobotsTXT = true

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# 项目版本
[params]
  version = '0.3.0'
  author = 'Semon'

# 多语言配置
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    title = 'Awesome Video Prompts'
    weight = 1
    languageName = 'English'
    contentDir = 'content/en'
    [languages.en.params]
      description = 'A collection of awesome video prompts'

  [languages.zh-cn]
    title = '精彩视频提示词'
    weight = 2
    languageName = '简体中文'
    contentDir = 'content/zh-cn'
    [languages.zh-cn.params]
      description = '精彩视频提示词合集'

[module]
  [[module.mounts]]
    source = 'content'
    target = 'content/en'
    lang = 'en'
  [[module.mounts]]
    source = 'content'
    target = 'content/zh-cn'
    lang = 'zh-cn'

# 多语言配置
